import { ProcurementRequest, RepairRequest, RequestStatus, UrgencyLevel } from '../types';

export const DEPARTMENTS = [
  'Ban giám đốc',
  'Phòng DVKH',
  'Phòng KHDN',
  'Phòng Bán lẻ',
  'Phòng HTTD',
  'Phòng TCTH',
  'Phòng Ninh Thành',
  'Phòng Yên Khánh',
  'Phòng Kim Sơn',
  'Phòng Gia Viễn',
];

export const EQUIPMENT_LIST = [
  'Bàn làm việc lãnh đạo',
  'Bàn làm việc nhân viên',
  'Bình chữa cháy',
  'Bộ bàn ghế tiếp khách',
  'Camera',
  'Cây nước nóng lạnh',
  'Ghế chờ khách hàng',
  'Ghế xoay lưới',
  'Giá sắt',
  'Hộc tủ',
  'Két sắt',
  'Máy bó tiền (quấn thếp)',
  'Máy bó tiền tự động',
  'Máy cà thẻ (POS)',
  'Máy đếm tiền',
  'Máy Điều hòa',
  'Máy đóng chứng từ',
  'Máy hủy tài liệu',
  'Máy in laser',
  'Máy in sổ',
  'Máy Photocopy',
  'Máy quét tốc độ cao',
  'Máy tính bảng',
  'Máy tính casio',
  'Máy vi tính để bàn',
  'Máy vi tính xách tay',
  'Phích điện',
  'Quạt Jiplai',
  'Thang nhôm',
  'Thiết bị mạng',
  'Tivi',
  'Tủ tài liệu',
  'UPS',
  'Tài sản khác',
];

export const URGENCY_LEVELS: UrgencyLevel[] = ['Thấp', 'Trung Bình', 'Cao', 'Rất Cao'];

export const STATUS_OPTIONS: RequestStatus[] = ['Đề xuất', 'Đang xử lý', 'Từ chối', 'Hoàn thành xử lý'];

export const SAMPLE_REPAIR_REQUESTS: RepairRequest[] = [
  {
    id: 'SC-2026-0001',
    fullName: 'Nguyễn Văn Hải',
    department: 'Phòng DVKH',
    assetName: 'Máy đếm tiền Glory 8880',
    condition: 'Đếm bị kẹt tiền, màn hình chập chờn khi cắm nguồn',
    reportDate: '2026-08-08',
    proposal: 'Thay dây curoa và kiểm tra lại nguồn máy đếm tiền',
    urgency: 'Cao',
    status: 'Đang xử lý',
    handler: 'Trần Minh Đức - Phòng TCTH',
    note: 'Đã liên hệ đơn vị bảo hành, dự kiến xong trong ngày',
    createdAt: '2026-08-08T08:30:00.000Z',
  },
  {
    id: 'SC-2026-0002',
    fullName: 'Lê Thị Thu Thảo',
    department: 'Phòng KHDN',
    assetName: 'Máy in laser HP LaserJet Pro',
    condition: 'Kẹt giấy liên tục khi in hợp đồng tín dụng',
    reportDate: '2026-08-09',
    proposal: 'Thay bao lụa và lô cuốn giấy',
    urgency: 'Trung Bình',
    status: 'Đề xuất',
    createdAt: '2026-08-09T09:15:00.000Z',
  },
  {
    id: 'SC-2026-0003',
    fullName: 'Phạm Quốc Hùng',
    department: 'Phòng Ninh Thành',
    assetName: 'Máy Điều hòa Panasonic 18000BTU',
    condition: 'Không mát, có tiếng kêu to ở cục nóng',
    reportDate: '2026-08-05',
    proposal: 'Vệ sinh lưới lọc và nạp gas bổ sung',
    urgency: 'Cao',
    status: 'Hoàn thành xử lý',
    handler: 'Nguyễn Tiến Dũng',
    completionDate: '2026-08-06',
    note: 'Đã bảo dưỡng toàn bộ hệ thống điều hòa',
    createdAt: '2026-08-05T10:00:00.000Z',
  },
];

export const SAMPLE_PROCUREMENT_REQUESTS: ProcurementRequest[] = [
  {
    id: 'MS-2026-0001',
    fullName: 'Nguyễn Thị Mai',
    department: 'Phòng Bán lẻ',
    equipmentName: 'Máy đếm tiền',
    quantity: 2,
    category: 'Máy đếm tiền phát hiện tiền giả cao cấp Silicon',
    reason: 'Trang bị cho 2 quầy giao dịch viên mới tăng cường đợt cuối năm',
    description: 'Tốc độ đếm > 1000 tờ/phút, có khay đếm tự động, cảm biến hồng ngoại',
    requestDate: '2026-08-07',
    proposedDate: 'Trong tháng 08/2026',
    status: 'Đang xử lý',
    handler: 'Phạm Anh Tuấn',
    note: 'Đang trình Ban Giám Đốc phê duyệt hạn mức kinh phí',
    createdAt: '2026-08-07T11:20:00.000Z',
  },
  {
    id: 'MS-2026-0002',
    fullName: 'Đỗ Hoàng Nam',
    department: 'Phòng HTTD',
    equipmentName: 'Máy quét tốc độ cao',
    quantity: 1,
    category: 'Máy scan 2 mặt tự động Canon DR-C225W',
    reason: 'Phục vụ số hóa tài liệu tín dụng lưu trữ lâu dài',
    description: 'Tốc độ 25 trang/phút, kết nối Wifi/USB, nạp tài liệu tự động 30 tờ',
    requestDate: '2026-08-09',
    proposedDate: 'Tuần tới',
    status: 'Đề xuất',
    createdAt: '2026-08-09T14:00:00.000Z',
  },
  {
    id: 'MS-2026-0003',
    fullName: 'Vũ Minh Tuấn',
    department: 'Phòng Yên Khánh',
    equipmentName: 'Ghế xoay lưới',
    quantity: 5,
    category: 'Ghế xoay văn phòng khung thép mạ chrome, lưới thoáng khí',
    reason: 'Thay thế ghế quầy giao dịch đã hỏng rách da',
    description: 'Màu xanh đen, tay vịn cố định, chân xoay bánh xe chịu lực',
    requestDate: '2026-08-02',
    proposedDate: 'Trước 15/08/2026',
    status: 'Hoàn thành xử lý',
    handler: 'Trần Văn Cường',
    completionDate: '2026-08-05',
    note: 'Đã bàn giao đủ 05 ghế cho phòng Yên Khánh',
    createdAt: '2026-08-02T15:45:00.000Z',
  },
];
